### ISSUE TITLE
Shakhid_PER-U11-T1

### ISSUE THREAD

**Issue by shakhid** [FrederikVandenBussche/projectwerk-hbo5#10]
![2017-05-16_210047](https://cloud.githubusercontent.com/assets/22688040/26123445/3a1e98c0-3a7b-11e7-84fe-6dd5205ebfac.png)
![2017-05-16_210136](https://cloud.githubusercontent.com/assets/22688040/26123443/3a1b10c4-3a7b-11e7-895b-5860571df04f.png)
![2017-05-16_210146](https://cloud.githubusercontent.com/assets/22688040/26123444/3a1ba728-3a7b-11e7-86e7-0f85f18e1943.png)

**Comment by FrederikVandenBussche** [comment]
Door de traagheid van de databankconnectie plaatste ik veel objecten als attribuut in de session. Op deze manier kon de databankconnectie assyncroon verlopen. Dit werd echter niet zorgvuldig gedaan en daarenboven werd het cpugebruik op de server te hoog. 
Aanpassing : geen objecten meer in de session.
