### ISSUE TITLE
BEN

### ISSUE THREAD

**Issue by BenjaminSalens** [FrederikVandenBussche/projectwerk-hbo5#15]
bij nieuw adres toevoegen, nullpointerexception
<img width="792" alt="kla-u10-t5" src="https://cloud.githubusercontent.com/assets/28739015/26124065/721adac0-3a7d-11e7-8a1f-818c76cdfdd1.PNG">

**Comment by FrederikVandenBussche** [comment]
Door de traagheid van de databankconnectie plaatste ik veel objecten als attribuut in de session. Op deze manier kon de databankconnectie assyncroon verlopen. Dit werd echter niet zorgvuldig gedaan en daarenboven werd het cpugebruik op de server te hoog. 
Aanpassing : geen objecten meer in de session.
